gallandarakhneorg/afc

ui/android/src/main/java/org/arakhne/afc/ui/android/colorpicker/ColorPickerDialog.java
squid:S2185 - “Silly math should not be performed”. 
https://dev.eclipse.org/sonar/rules/show/squid:S2185
Fevzi Ozgul
=>  Fixing squid: S2185 Silly math should not be performed

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/Ellipse2afp.java
=> Release/string literals should not be duplicated  fix 1

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/PathElement2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/PathElement2ifx.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/d/PathElement2d.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/i/PathElement2i.java
squid:S2097 - “ ""equals(Object obj)"" should test argument type ”. 
This PR will remove 90 min TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2097
Fevzi Ozgul
=> Fixing squid S2097  "equals(Object obj)" should test argument type

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/AbstractRectangularShape2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Circle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/MultiShape2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/OrientedRectangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Parallelogram2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Rectangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/RoundRectangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Segment2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Triangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Tuple2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/AbstractRectangularShape2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Circle2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/MultiShape2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/PathElement2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Rectangle2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Segment2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Tuple2ifx.java
"This pull request is focused on resolving occurrences of Sonar rule 
squid:S2183 - “Ints and longs should not be shifted by more than their number of bits-1”. 
This PR will remove 105 min TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2183
Fevzi Ozgul
=> Fixing squid: S2183  Ints and longs should not be shifted by more than their number of bits-1

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Path2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Path2ifx.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/i/Path2i.java
squid:ForLoopCounterChangedCheck - “"for" loop stop conditions should be invariant”. 
https://dev.eclipse.org/sonar/rules/show/squid:ForLoopCounterChangedCheck
Fevzi Ozgul
=> Fixing squid:ForLoopCounterChangedCheck  for loop stop conditions should be invariant fix 2

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/OrientedRectangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Parallelogram2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Path2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Triangle2dfx.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/d/Vector2d.java
=> Fixing squid S1192 String literals should not be duplicated Fix 4

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/OrientedRectangle2afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/Parallelogram2afp.java
This PR will remove 64 min.
Fevzi Ozgul
=> Fixing squid :S1192 String literals should not be duplicated Part 3

core/math/src/main/java/org/arakhne/afc/math/matrix/Matrix2d.java, core/math/src/main/java/org/arakhne/afc/math/matrix/Matrix3d.java, core/math/src/main/java/org/arakhne/afc/math/matrix/Matrix4d.java
=> Fixing squid S1192 String literals should not be duplicated Fix 7

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Path2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/PathElement2ifx.java
=> Fixing squid: S1192 String literals should not be duplicated Fix 6

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/MultiShape2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/MultiShape2ifx.java
squid:S2160 - “Subclasses that add fields should override ""equals""”. 
This PR will remove 60 min. TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2160
Fevzi Ozgul
=> Fixing squid: S2160 Subclasses that add fields should override "equals"

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/Path2afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/RoundRectangle2afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ai/Path2ai.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/d/PathElement2d.java
=> Fixing squid: S1192 String literals should not be duplicated Fix 3

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/PathElement2dfx.java
=> Fixing squid: S1192 String literals should not be duplicated Fix 5

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ai/PathShadow2ai.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ai/Rectangle2ai.java, core/util/src/main/java/org/arakhne/afc/progress/DefaultProgression.java
squid:S2184 - “Math operands should be cast before assignment”. 
https://dev.eclipse.org/sonar/rules/show/squid:S2184
Fevzi Ozgul
=> Fixing squid: S2184 Math operands should be cast before assignment

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/Segment2afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/i/Path2i.java
squid:ForLoopCounterChangedCheck - “"for" loop stop conditions  should be invariant”. 
This PR will remove 260 min TD.
https://dev.eclipse.org/sonar/rules/show/squid:ForLoopCounterChangedCheck
Fevzi Ozgul
=> Fixing squid: ForLoopCounterChangedCheck  "for" loop stop conditions  should be invariant part 1

core/math/src/main/java/org/arakhne/afc/math/graph/DepthFirstGraphCourseModel.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/AbstractInfixDepthFirstTreeIterator.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/AbstractPostfixDepthFirstTreeIterator.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/AbstractPrefixDepthFirstTreeIterator.java, core/vmutils/src/main/java/org/arakhne/afc/vmutil/ThreadServiceFinder.java
squid:S1149 - “Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used ”. 
This PR will remove 100min TD.
https://dev.eclipse.org/sonar/rules/show/squid:S1149
Fevzi Ozgul
=> Fixing squid: S1149 Synchronized classes Vector, Hashtable, Stack and StringBuffer should not be used Part 1

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ImmutablePoint2D.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ImmutableVector2D.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/Tuple2D.java
This PR is improved version of PR#53 which we had  closed to produce  an new PR using Java way of equals method creation. 
squid:S2259 - “Null pointers should not be dereferenced”. 
This PR will remove 80 min TD: 
https://dev.eclipse.org/sonar/rules/show/squid:S2259
Fevzi Ozgul
=> Fixing squid: S229 Null pointers should not be deferenced  Part 1--- PR#53  reworked

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/d/PathElement2d.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/i/PathElement2i.java
squid:S2259 - “Null pointers should not be dereferenced”. 
This PR will remove 100 min TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2259
Fevzi Ozgul
=> Fixing squid: S2259 Null pointers should not be dereferenced Part 2  PR#53 reworked as agreed.

advanced/attributes/src/main/java/org/arakhne/afc/attrs/attr/AttributeValueImpl.java, core/math/src/main/java/org/arakhne/afc/math/tree/node/AbstractParentlessTreeNode.java, core/vmutils/src/main/java/org/arakhne/afc/vmutil/MACNumber.java, core/vmutils/src/main/java/org/arakhne/afc/vmutil/VMCommandLine.java, core/vmutils/src/main/java/org/arakhne/afc/vmutil/file/URLConnection.java, core/vmutils/src/test/java/org/arakhne/afc/vmutil/VMCommandLineTest.java
squid:S1168- “ Empty arrays and collections should be returned instead of null”. 
You can find more information about the issues here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1168
Fevzi Ozgul
=> Fixing squid: S1168 Empty arrays and collections should be returned instead of null

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ai/Path2ai.java
This PR will remove 45 min of TD.
Fevzi Ozgul
=> Fixing squid: S1854 Dead stores should be removed part 2

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/AbstractRectangularShape2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Circle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/OrientedPoint2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/OrientedRectangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Parallelogram2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Path2dfx.java
"This pull request is focused on resolving occurrences of Sonar rule 
squid:S1602 - “Lamdbas containing only one statement should not nest this statement”. 
This PR will remove 30 min of TD.
Fevzi Ozgul
=> Fixing squid : S1602 Lamdbas containing only one statement should not nest this statement in a block  part 1

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/PathElement2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Rectangle2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Segment2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Triangle2dfx.java
squid:S1602 - “Lamdbas containing only one statement should not nest this statement in a block”. 
This PR will remove 45 min of TD.
Fevzi Ozgul
=> Fixing squid: S1602 Lamdbas containing only one statement should not nest this statement in a block- part 2

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Vector2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Circle2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/OrientedPoint2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/PathElement2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Rectangle2ifx.java
squid:S1602 - “Lamdbas containing only one statement should not nest this statement in a block”. 
This PR will remove 50  min of TD.
Fevzi Ozgul
=> Fixing squid: S1602 Lamdbas containing only one statement should not nest this statement in a block part 3

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Segment2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Vector2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/Path3dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/PathElement3dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/RectangularPrism3dfx.java
squid:S1602 - “Lamdbas containing only one statement should not nest this statement”. 
This PR will remove 50 min of TD.
Fevzi Ozgul
=> Fixing squid: S1602 Lamdbas containing only one statement should not nest this statement in a block part 4

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/Segment3dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/Sphere3dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/Vector3dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/ifx/AbstractRectangularShape3ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/ifx/RectangularPrism3ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/ifx/Segment3ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/ifx/Sphere3ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/ifx/Vector3ifx.java
squid:S1602 - “Lamdbas containing only one statement should not nest this statement”. 
This PR will remove 50 min of TD.
Fevzi Ozgul
=> Fixing squid: S1602 Lamdbas containing only one statement should not nest this statement in a block part 5 final

advanced/attributes/src/main/java/org/arakhne/afc/attrs/attr/AttributeType.java
squid:S1151 - “""switch case"" clauses should not have too many lines”. 
This PR will remove 70min TD.
I have created methods where possible for case clauses. In a future PR, we could refactor those methods by searching similarities between them and end up with less methods. 
Fevzi Ozgul
=> Fixing squid: S1151 "switch case" clauses should not have too many lines part 1

core/references/src/main/java/org/arakhne/afc/references/AbstractReferencedSet.java, core/references/src/main/java/org/arakhne/afc/references/AbstractReferencedValueMap.java
This PR will remove 45min of TD.
Fevzi Ozgul
=> Fixing squid:S1854 Dead stores should be removed part 6

core/vmutils/src/main/java/org/arakhne/afc/vmutil/locale/Locale.java
This PR will remove 75min of TD.
Fevzi Ozgul
=> Fixing squid: S1854 Dead stores should be removed part 8

advanced/agentmotion/src/main/java/org/arakhne/afc/agentmotion/AligningMotionAlgorithm.java, advanced/agentmotion/src/main/java/org/arakhne/afc/agentmotion/ArrivingMotionAlgorithm.java, advanced/agentmotion/src/main/java/org/arakhne/afc/agentmotion/FacingMotionAlgorithm.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/d/ShapeGeometryChangeListener.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/i/ShapeGeometryChangeListener.java, core/math/src/main/java/org/arakhne/afc/math/graph/astar/AStarHeuristic.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/BroadFirstIterationListener.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/DataSelector.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/NodeSelector.java
squid:S1609 - “@FunctionalInterface annotation should be used to flag Single Abstract Method interfaces”. 
https://dev.eclipse.org/sonar/rules/show/squid:S1609
Fevzi Ozgul
=> Fixing squid: S1609 @FunctionalInterface annotation should be used to flag Single Abstract Method interfaces

core/math/src/main/java/org/arakhne/afc/math/geometry/d3/afp/PathShadow3afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/ai/PathShadow3ai.java
squid:S1066 - “Collapsible ""if"" statements should be merged”. 
This PR will remove 30 min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S1066
Fevzi Ozgul
=> Fixing squid: S1066 Collapsible 'if' statements should be merged

core/math/src/main/java/org/arakhne/afc/math/tree/AbstractTree.java
squid:S1604 - “Anonymous inner classes containing only one method should become lambdas”. 
This PR will reduce 40  min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S1604
Fevzi Ozgul
=> Fixing squid: S1604 Anonymous inner classes containing only one method should become lambdas part 1

advanced/attributes/src/main/java/org/arakhne/afc/attrs/attr/AttributeValueImpl.java
squid:S1151 - “""switch case"" clauses should not have too many lines”. 
This PR will remove 35 min of TD.
Fevzi Ozgul
=> Fixing squid: S1151 Swictch clauses should not have too many lines part 2

advanced/attributes/src/main/java/org/arakhne/afc/attrs/attr/AttributeValueImpl.java
squid:S1151 - “""switch case"" clauses should not have too many lines”.
This PR will reduce 70 min of TD. 
Fevzi Ozgul
=> Fixing squid: S1151 Switch clauses should not have too many lines part 3

advanced/attributes/src/main/java/org/arakhne/afc/attrs/attr/AttributeType.java
squid:MethodCyclomaticComplexity - “""Methods should not be too complex”. 
You can find more information about the issue here:
This PR will remove 41 min of TD. 
https://dev.eclipse.org/sonar/rules/show/squid:MethodCyclomaticComplexity
Fevzi Ozgul
=> Fixing squid:MethodCyclomaticComplexity Methods should not be too complex part 2

core/math/src/main/java/org/arakhne/afc/math/matrix/Matrix3d.java
This PR will remove 60 min of TD.
Fevzi Ozgul
=> Fixing squid: S1854 Dead stores shold be removed fix 2

advanced/attributes/src/main/java/org/arakhne/afc/attrs/collection/AbstractBufferedAttributeProvider.java, advanced/attributes/src/main/java/org/arakhne/afc/attrs/collection/BufferedAttributeCollection.java, advanced/attributes/src/main/java/org/arakhne/afc/attrs/collection/HeapAttributeCollection.java, core/inputoutput/src/main/java/org/arakhne/afc/inputoutput/xml/ColorFormatException.java, core/inputoutput/src/main/java/org/arakhne/afc/inputoutput/xml/DateFormatException.java, core/inputoutput/src/main/java/org/arakhne/afc/inputoutput/xml/XMLUtil.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/afp/PathShadow3afp.java
squid:S00117 - “ Local variable and method parameter names should comply with a naming convention”. 
This PR will remove 40 min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S00117
Fevzi Ozgul
=> Fixing squid: S00117 Local variable and method parameter names should comply with a naming convention part 1

core/math/src/main/java/org/arakhne/afc/math/geometry/d3/ai/PathShadow3ai.java, core/math/src/main/java/org/arakhne/afc/math/graph/DepthGraphIterator.java, core/math/src/main/java/org/arakhne/afc/math/graph/Graph.java, core/math/src/main/java/org/arakhne/afc/math/graph/SubGraph.java, core/math/src/main/java/org/arakhne/afc/math/graph/simple/SGraph.java, core/math/src/main/java/org/arakhne/afc/math/matrix/Matrix3d.java
squid:S00117 - “ Local variable and method parameter names should comply with a naming convention”.
This PR will remove 62 min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S00117
Fevzi Ozgul
=> Fixing squid: S00117 Local variable and method parameter names should comply with a naming convention fix 2

core/math/src/main/java/org/arakhne/afc/math/matrix/Matrix3d.java, maven/maventools/src/main/java/org/arakhne/maven/AbstractArakhneMojo.java
This PR will remove 60min of TD.
Fevzi Ozgul
=> Fixing squid: S1854 Dead stores should be removed fix 4

advanced/attributes/src/main/java/org/arakhne/afc/attrs/attr/AttributeValueImpl.java
squid:S1151 - “""switch case"" clauses should not have too many lines”.
This PR will reduce 25 min of TD. 
Fevzi Ozgul
=> Fixing squid:S1151 Switch case clauses should not have too many lines

advanced/attributes/src/main/java/org/arakhne/afc/attrs/collection/MultiAttributeCollection.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/BasicPathShadow2afp.java
squid:S1151 - “""switch case"" clauses should not have too many lines”.
This PR will reduce 40 min of TD. 
Fevzi Ozgul
=> Fixing squid: S1151 Switch case clauses should not have too many lines fix new 2

advanced/attributes/src/main/java/org/arakhne/afc/attrs/collection/MultiAttributeCollection.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/ai/RectangularPrism3ai.java, core/math/src/main/java/org/arakhne/afc/math/tree/iterator/PrefixDepthFirstTreeIterator.java, core/math/src/main/java/org/arakhne/afc/math/tree/node/AbstractParentlessTreeNode.java, core/references/src/main/java/org/arakhne/afc/references/AbstractReferencedValueMap.java
squid:S2178 - “Short-circuit logic should be used in boolean contexts”. 
TD removal: 50min
https://dev.eclipse.org/sonar/rules/show/squid:S2178
Fevzi Ozgul
=> Fixing squid: S2178 Short-circuit logic should be used in boolean contexts

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Segment2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Segment2ifx.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/ImmutablePoint3D.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/ImmutableVector3D.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/Vector3D.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/d/RectangularPrism3d.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/i/AbstractPrism3i.java
squid:S2183 - “Ints and longs should not be shifted by more than their number of bits-1”. 
This PR will remove 70min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2183
Fevzi Ozgul
=> Fixing squid: S2183 Ints and longs should not be shifted by more than their number of bits-1

advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/dfx/Path2dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d2/ifx/Path2ifx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/dfx/Path3dfx.java, advanced/mathfx/src/main/java/org/arakhne/afc/math/geometry/d3/ifx/Path3ifx.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/MultiShape2afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d2/ai/MultiShape2ai.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/afp/MultiShape3afp.java, core/math/src/main/java/org/arakhne/afc/math/geometry/d3/ai/MultiShape3ai.java, core/math/src/main/java/org/arakhne/afc/math/tree/node/AbstractParentlessTreeNode.java
squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. 
This PR will remove 66min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Fevzi Ozgul
=> Fixing squid: S1155 Collection.isEmpty() should be used to test for emptiness

core/vmutils/src/main/java/org/arakhne/afc/vmutil/FileSystem.java
squid:S2093 - “Try with resources should be used”. 
This PR will remove 30min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2093
Fevzi Ozgul
=> Fixing squid: S2093 Try with resources should be used

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/OrientedRectangle2afp.java
squid:S1151 - “""switch case"" clauses should not have too many lines”. 
This PR will remove 30min of TD.
Fevzi Ozgul
=> Fixing squid: S1151 "switch case" clauses should not have too many lines

core/math/src/main/java/org/arakhne/afc/math/geometry/d2/afp/Parallelogram2afp.java
squid:S1151 - “""switch case"" clauses should not have too many lines”. 
This PR will remove 30min of TD.
Fevzi Ozgul
=> Fixing squid: S1151 Switch case clauses hsould not have too many lines

core/testtools/src/main/java/org/arakhne/afc/testtools/AbstractTestCase.java
squid:S2583 - “ Conditions should not unconditionally evaluate to ""TRUE"" or to ""FALSE"" ”. 
This PR will remove 60 min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2583
Fevzi Ozgul
=> Fixing squid: S2583  Conditions should not unconditionally evaluate to "TRUE" or to "FALSE"

core/math/src/main/java/org/arakhne/afc/math/tree/node/NaryTreeNode.java
squid:S2583 - “ Conditions should not unconditionally evaluate to ""TRUE"" or to ""FALSE"" ”. 
This PR will remove 30min of TD.
https://dev.eclipse.org/sonar/rules/show/squid:S2583
Fevzi Ozgul
=> Fixing squid:S2583 Conditions should not unconditionally evaluate to "TRUE" or to "FALSE" part 2
